### ISSUE TITLE
Improve TSDF fusion

### ISSUE THREAD

**Issue by hbb1** [YuxueYang1204/TrimGS#1]
Hi, good job.

I noticed that you're also using TSDF fusion. In case you're not aware, I recently made [a small fix](https://github.com/hbb1/2d-gaussian-splatting/commit/21a32f11449f0e787bc4b622e7e13c736086fa5b) to TSDF fusion, resulting in better geometry reconstruction. For example, the chamfer distance decreased from 0.80 to 0.74 in the DTU dataset. I think this could also enhance your results!

Cheers!

**Comment by Abyssaledge** [comment]
Hi binbin,
Thank you so much for reminding us! We will try it later and update the results. Btw, thanks for your great work 2DGS which inspires us a lot and we believe it will definitely become an influential art!

**Comment by hbb1** [comment]
Thank you for your kind words! I also learned a lot from yours and believe that it will be really helpful for any Gaussians! Looking forward to your code release. Congrats!

**Comment by YuxueYang1204** [comment]
Thank you for your kind suggestion! It does enhance the performance of Trim2DGS on DTU dataset from 0.72 to 0.69. We appreciate your valuable help!
