### ISSUE TITLE
Training Times 

### ISSUE THREAD

**Issue by DiamondGlassDrill** [YuxueYang1204/TrimGS#10]
First of all congrats to the stunning results and impressive work in both fields 2D- and 3DGS.

I tried to find the training times in the paper and the webpage but could not find them.

Could u provide for some scenes the training times and hardware GPU used, so one can have a feel of the overall performance?

Thanks in advance.

**Comment by Abyssaledge** [comment]
Thanks for your attention. We train all scenes with 3090 GPU. If I do not misunderstand the "training times", the schedule for all experiments is 30k 2DGS/3DGS training and 7k fine-tuning with our trimming strategy.

**Comment by DiamondGlassDrill** [comment]
@Abyssaledge thanks for your reply.
I thought about the actual training times e.g. 30k for x-minutes and 7k with x-minutes, so something tangible. 
Thanks im advance.

**Comment by YuxueYang1204** [comment]
Hi @DiamondGlassDrill . We have tested the training time of TrimGS on the DTU dataset. The training time for 30K iterations is consistent with the time reported in the 3DGS and 2DGS papers. Specifically, 3DGS averages 11 minutes per scan, and 2DGS averages 18 minutes per scan. For the subsequent 7K fine-tuning, 3DGS averages 7 minutes per scene, and 2DGS averages 2.5 minutes per scene. We hope this information can help you.

**Comment by DiamondGlassDrill** [comment]
@YuxueYang1204 wonderful. Thanks for comming back. Indeed this solves my question. Great work!
