### ISSUE TITLE
Some questions about 3DGS

### ISSUE THREAD

**Issue by leomessi999** [YuxueYang1204/TrimGS#15]
![image](https://github.com/YuxueYang1204/TrimGS/assets/129869043/c73af496-f01a-4271-96df-b39d5a01d2b2)
![image](https://github.com/YuxueYang1204/TrimGS/assets/129869043/b14e80c5-9d44-4eb7-8e09-72d0bc6e8dda)

Why is there a difference between new_scaling in the function densify_and_split and new_scaling in function densify_and_self_split [:, 1:]

**Comment by leomessi999** [comment]
这个scale不是有三个值吗？为什么这样做呀？希望您可以抽出时间回答，万分感谢

**Comment by YuxueYang1204** [comment]
Hi @leomessi999 ! During the training of Trim3DGS, we designed [FlattenGaussianModel](https://github.com/YuxueYang1204/TrimGS/blob/ba29b837c4f17e802288940b9f5ada095fa0429f/Trim3DGS/scene/gaussian_model.py#L503) that inherits from the original GaussianModel. Specifically, we set the first scale to `eps_s0` (i.e., 1e-8). This modification allows the Gaussian primitives to approximate planes, making it easier to define the normal vector. At the same time, it will not change the structure of `point_cloud.ply`, ensuring that the trained Gaussian model can be visualized in the original 3DGS renderer.

**Comment by leomessi999** [comment]
感谢感谢，如果我想要将这个加密策略用到原始gs上，是不是直接把[:,:-1]去掉就行？

**Comment by YuxueYang1204** [comment]
可能不是这么简单，因为你需要定义法向量，如果取最短轴作为法向量的话，每次迭代对尺度优化都需要对法向量轴作更改。

It might not be trivial because you need to define the normal vector. If you take the shortest axis as the normal vector, you would need to adjust the normal vector axis after each iteration of scale optimization.

**Comment by leomessi999** [comment]
好的，谢谢
