### ISSUE TITLE
Scale-driven Densification

### ISSUE THREAD

**Issue by asd351012** [YuxueYang1204/TrimGS#17]
Thank you for your excellent work. Could you please explain the differences between Scale-driven Densification and the original 3DGS Densification?

**Comment by YuxueYang1204** [comment]
Hi @asd351012 ! The main difference between scale-driven densification and the original 3DGS densification is that the former ignores gradient and densifies solely based on Gaussian scale. For more details, you can refer to section 4.2 of [our paper](https://arxiv.org/abs/2406.07499).

**Comment by asd351012** [comment]
After reading the paper and your response, I understand now. Thank you for your answer.
