### ISSUE TITLE
About Trim2DGS Codes

### ISSUE THREAD

**Issue by utkuoguzman** [YuxueYang1204/TrimGS#2]
Hi,
I just wanted to ask, will you also upload the Trim2DGS codes as well?
Thanks!

**Comment by Abyssaledge** [comment]
Of course, as shown in the to-do list, we will release trim2dgs in one week. Now, we are trying to refactor the code to make the two methods compatible in a shared environment. Thus the users could checkout to different methods without reinstallation.
