### ISSUE TITLE
texture of mesh

### ISSUE THREAD

**Issue by leewoosub** [YuxueYang1204/TrimGS#7]
Thank you so much for sharing amazing works!
I followed the instructions to make my own meshes. Finally, I get the mesh file (.ply) but I can't find any uv map when I import the ply file to Blender.
Is the ply file contain the texture of mesh? If not, how can I get the texture?

**Comment by LyBQck** [comment]
Thank you for your kind words! The mesh file(.ply) generated by our method already contains texture. However, some configurations are necessary to render the textured mesh when using blender GUI. For convenience, we share scripts for rendering images and videos in our demo using bpy in Python. We will release them by pulling requests soon.

**Comment by Abyssaledge** [comment]
@leewoosub  Hello, we have released the blender rendering scripts. Feel free to contact us if you have further questions.

**Comment by leewoosub** [comment]
Thank you so much!
